<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <ProduceReferenceAssembly>True</ProduceReferenceAssembly>
    <AssemblyName>Valheim.WhereAmI</AssemblyName>
    <Authors>A Sharp Pen</Authors>
	<Version>1.0.2</Version>
	  <LangVersion>preview</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NETStandard.Library" Version="2.0.3" />
    <PackageReference Include="Valheim.SpawnThat" Version="1.2.19" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>..\..\LibsStripped\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="assembly_utils">
      <HintPath>..\..\LibsStripped\assembly_utils.dll</HintPath>
    </Reference>
    <Reference Include="assembly_valheim">
      <HintPath>..\..\LibsStripped\assembly_valheim.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>..\..\LibsStripped\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\LibsStripped\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\LibsStripped\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\..\LibsStripped\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>..\..\LibsStripped\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\LibsStripped\UnityEngine.UI.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
